### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by ak-karimzai** [shimmer-ghq/DeepFidelity#1]
pretrained models are avalible?

is it possible to test just with one sample and detect it?

**Comment by shimmer-ghq** [comment]
Hello, we have provided pre-trained models [here](https://github.com/shimmer-ghq/DeepFidelity?tab=readme-ov-file#results). You can download them and modify the file path in `demo.py` to the actual path where you store the files.

**Comment by shimmer-ghq** [comment]
To test a sample, you can provide a CSV file that includes: `img` (the path to the image being tested) and `score` (a randomly set score, just for format matching). Then, modify this line in `demo.py`: `test_dataset = FakeFaceDataset(csv_file=r'/code/SSAAFormer/dataset/test_fqa.csv')    # 2/` to the path of your CSV file. The test results will be output to a CSV file, the path of which is specified at `csv_res = r'/code/SSAAFormer/test_result/result_svr.csv'  # 4/`.
