### ISSUE TITLE
RuntimeError: Unknown model (uniformer_large_ls)

### ISSUE THREAD

**Issue by ZZ00325** [shimmer-ghq/DeepFidelity#2]
hello, i got the erro, Please tell me how to solve?

raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (uniformer_large_ls)

**Comment by shimmer-ghq** [comment]
Sorry, we mistakenly deleted a file during the upload process. To fix this issue, simply add an __init__.py file in the token_labeling/tlt/models directory. We have already resolved this issue.
